#! /bin/sh

### AUTOSTART ###

pgrep -x sxhkd > /dev/null || sxhkd &

xwallpaper --stretch /home/kuruvilla/pictures/wallpapers/nasa-kDsNr-vu7ms-unsplash.jpg &

$HOME/.config/polybar/launch.sh &

# Something to do with monitors

bspc monitor -d 1 2 3 4 5 6 7 8 9

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    0
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                any
bspc config split_ratio                   0.52
bspc config borderless_monocle            true
bspc config gapless_monocle               true
#bspc config focus_by_distance             true
bspc config focus_follows_pointer         false
#bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		  "#3B4252"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	  "#ebcb8b"
bspc config presel_feedback_color	  "#88c0d0"
#bspc config urgent_border_color 	  "#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

bspc rule -a 'Gimp' desktop='^8' state=floating follow=on
# How do I make all firefox PiP windows float?
bspc rule -a 'Toolkit:firefox'
bspc rule -a mpv state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
